version: '3.3'

services:
  pypi-server:
    build: .
    image: avicii-local-pypi:1.0
    container_name: avicii_local_pypi
    volumes:
      # Mount the local folder for development/updates (optional when running baked image offline)
      - ./packages:/data/packages
    ports:
      - "8080:8080"
    restart: always

